swagger: "2.0"
info:
  description: "This is for the Creation of community"
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: localhost:3000
basePath: "/v2"
tags:
- name: "circle"
  description: "Everything about circle"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"

schemes:
- "http"
paths:
  /circle:
    post:
      tags:
      - "circle"
      summary: "Add a new circle"
      description: ""
      operationId: "addCircle"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/circle"
      responses:
        405:
          description: "Invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  
  /circle/{circleId}:
    delete:
      tags:
      - "circle"
      summary: "Deletes a circle"
      description: ""
      operationId: "deletePet"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "circleId"
        in: "path"
        description: "Circle id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Circle not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://localhost:3001/"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  
  circle:
    type: "object"
    properties:
      id:
        type: "string"
        format: "int64"
    xml:
      name: "Pet"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://localhost:3001/"