version: "2"
services:
  rest-api:
    image: rest-api
    build: rest-api
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: 172.23.238.134
      REDIS_PORT: 6379
      NAMESPACE_ROUTESMANAGER: routesmanager
      NAMESPACE_L1R: L1R
      NAMESPACE_MULTIPLEXER: multiplexer
      ZOOKEEPER_HOST: 172.23.238.134
      ZOOKEEPER_PORT: 2181
      ACTIVITIES_TOPIC: activities
      ROUTES_TOPIC: routes
      DSE_HOST: 172.23.238.134
      DSE_PORT: 9042
      DSE_KEYSPACE: testdb
      DAO: cassandra
      DEFAULT_CIRCLE: 10
  multiplexer:
    image: multiplexer
    build: multiplexer
    environment:
      REDIS_HOST: redis
      ZOOKEEPER_HOST: kafka 
      CONSUMER_GROUP: m1
  multiplexer-delivery:
    image: multiplexer-delivery
    build: multiplexer-delivery
    environment:
      REDIS_HOST: redis
      ZOOKEEPER_HOST: kafka
      DSE_HOST: dse
      DSE_KEYSPACE: testdb
      CONSUMER_GROUP: m1D
  l1r:
    image: l1r
    build: l1r
    environment:
      REDIS_HOST: redis
      ZOOKEEPER_HOST: kafka 
      CONSUMER_GROUP: activities
