version: "2"
services:
  multiplexer:
    image: multiplexer
    build: multiplexer
    links:
      - redis
      - kafka
    environment:
      REDIS_HOST: redis
      ZOOKEEPER_HOST: kafka
  multiplexer-delivery:
    image: multiplexer-delivery
    build: multiplexerDelivery
    links:
      - redis
      - kafka
      - dse
    environment:
      REDIS_HOST: redis
      ZOOKEEPER_HOST: kafka
      DSE_HOST: dse
      DSE_KEYSPACE: testdb
  redis:
    image: redis
    ports:
      - 6379:6379
  kafka:
    image: spotify/kafka
    build: spotify-kafka/kafka
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafka
  dse:
    image: cassandra
    ports:
      - 9042:9042
  produce:
    image: capacity-test-data
    build: capacity-test-data
    links:
      - redis
      - kafka
    environment:
      NUMBER_OF_MESSAGES: 1000000
      ZOOKEEPER_HOST: kafka
      REDIS_HOST: redis
