---
- hosts: localhost
  become: true
  roles:
    - geerlingguy.docker
  tasks:
    - name: install python-pip
      package:
        name: python-pip
        state: latest
    - name: install cqlsh
      pip:
        name: cqlsh
        state: latest
    - name: copy services docker-compose
      copy:
        src: ./files/docker-compose.yml
        dest: /tmp/docker-compose.yml
    - name: Start Services
      shell: docker-compose up -d
      args:
        chdir: /tmp/
